version: "3.4"
services:
  mysql-db:
    container_name: mysql-db
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: 'patient'
      # So you don't have to use root, but you can if you like
      # You can use whatever password you like
      MYSQL_USER: 'patientAdmin'
      MYSQL_PASSWORD: 'samrat123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  patient-service:
    container_name: patient-Container
    image: "patient-service"
    build:
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mysql-db
volumes:
  my-db:
    name: my-db